# Generated by Django 5.2.17 on 2026-10-05 08:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('widget', models.CharField(choices=[('checkbox', '复选框'), ('radio', '单选'), ('select', '下拉单选'), ('multiselect', '下拉多选')], default='checkbox', max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('source_lang', models.CharField(default='ru', max_length=10)),
                ('target_lang', models.CharField(default='zh', max_length=10)),
                ('status', models.CharField(choices=[('published', '已发布'), ('hidden', '已下架')], default='published', max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
            ],
            options={
                'ordering': ['work_id', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('editor', '标注员'), ('user', '普通用户')], default='user', max_length=16)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('institution', models.CharField(blank=True, default='', max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('defined_in_legacy', models.BooleanField(default=True, help_text='false: only appeared in legacy data')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='corpus.annotationgroup')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('target', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='annotationgroup',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_groups', to='corpus.corpus'),
        ),
        migrations.CreateModel(
            name='AlignGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('position', models.IntegerField(db_index=True, help_text='global reading order within the work')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='corpus.corpus')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='corpus.paragraph')),
            ],
            options={
                'ordering': ['work_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='corpus.aligngroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('filename', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='imports/')),
                ('status', models.CharField(choices=[('preview', '待确认'), ('done', '已导入'), ('failed', '失败'), ('cancelled', '已取消')], default='preview', max_length=16)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField()),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('result_count', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(help_text='order within paragraph for this version')),
                ('source', models.TextField()),
                ('target', models.TextField(blank=True, default='')),
                ('unsplit', models.BooleanField(default=False, help_text='whole paragraph never split into sentences')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='corpus.corpus')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='corpus.aligngroup')),
            ],
            options={
                'ordering': ['group_id', 'version__sort_order', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='SegmentAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.segment')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.annotationvalue')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='annotations',
            field=models.ManyToManyField(related_name='segments', through='corpus.SegmentAnnotation', to='corpus.annotationvalue'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('source', '原文'), ('translation', '译文')], max_length=16)),
                ('lang', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=200)),
                ('person', models.CharField(blank=True, default='', max_length=200)),
                ('bibliography', models.CharField(blank=True, default='', max_length=1000)),
                ('sort_order', models.IntegerField(default=0)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='corpus.corpus')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='segment',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='corpus.version'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_source', models.CharField(max_length=500)),
                ('title_target', models.CharField(blank=True, default='', max_length=500)),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='corpus.corpus')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='segment',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='corpus.work'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='corpus.work'),
        ),
        migrations.AddField(
            model_name='aligngroup',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='corpus.work'),
        ),
        migrations.AddConstraint(
            model_name='annotationvalue',
            constraint=models.UniqueConstraint(fields=('group', 'label'), name='uniq_value_label'),
        ),
        migrations.AddConstraint(
            model_name='annotationgroup',
            constraint=models.UniqueConstraint(fields=('corpus', 'name'), name='uniq_group_name'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='uniq_favorite'),
        ),
        migrations.AddIndex(
            model_name='segmentannotation',
            index=models.Index(fields=['value', 'segment'], name='corpus_segm_value_i_40e900_idx'),
        ),
        migrations.AddConstraint(
            model_name='segmentannotation',
            constraint=models.UniqueConstraint(fields=('segment', 'value'), name='uniq_segment_value'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['corpus', 'version'], name='corpus_segm_corpus__46a13e_idx'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['work'], name='corpus_segm_work_id_75e7d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='paragraph',
            constraint=models.UniqueConstraint(fields=('work', 'seq'), name='uniq_paragraph_seq'),
        ),
        migrations.AddIndex(
            model_name='aligngroup',
            index=models.Index(fields=['work', 'position'], name='corpus_alig_work_id_fd3ccb_idx'),
        ),
        migrations.AddConstraint(
            model_name='aligngroup',
            constraint=models.UniqueConstraint(fields=('paragraph', 'seq'), name='uniq_group_seq'),
        ),
    ]
