# Generated by Django 5.2.17 on 2026-10-05 08:13

from django.db import migrations

from corpus.fts import CREATE_SQL, DROP_SQL


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(CREATE_SQL, DROP_SQL),
    ]
