# Generated by Django 5.2.17 on 2026-10-05 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_segment_fts'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentannotation',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='segmentannotation',
            name='evidence',
            field=models.CharField(blank=True, default='', help_text='words the AI annotation rests on', max_length=300),
        ),
        migrations.AddField(
            model_name='segmentannotation',
            name='method',
            field=models.CharField(blank=True, default='', help_text='AI annotator that produced it', max_length=40),
        ),
        migrations.AddField(
            model_name='segmentannotation',
            name='origin',
            field=models.CharField(choices=[('human', '人工'), ('ai', 'AI')], db_index=True, default='human', max_length=8),
        ),
        migrations.AddField(
            model_name='segmentannotation',
            name='replaced',
            field=models.ForeignKey(blank=True, help_text='human value this AI annotation corrected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='corpus.annotationvalue'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='annotations',
            field=models.ManyToManyField(related_name='segments', through='corpus.SegmentAnnotation', through_fields=('segment', 'value'), to='corpus.annotationvalue'),
        ),
    ]
